server:
  port: 8080

spring:
  application:
    name: taste-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/taste_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  
  security:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    com.taste: DEBUG
    org.springframework.security: DEBUG

app:
  jwt:
    secret: your-super-secret-jwt-key-change-this-in-production
    expiration: 604800000 # 7 days in milliseconds
  
  upload:
    dir: uploads/
    max-size: 5242880 # 5MB

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.taste: INFO
    org.springframework.security: WARN